version: 2.1

jobs:
  flyway-build:
    # executor: flyway-ci
    docker:
      - image: kulmam92/flyway-azure:6.2.3
    steps:
      - checkout # check out the code in the project directory
      - run: ls sql
      - run: pwd
      # - run: flyway -user='gdhawas' -password='SFgrd0710*' -url='jdbc:snowflake://pm71396.ap-south-1.aws.snowflakecomputing.com/?db=QA_DB&warehouse=QA&schema=FLYWAY' -locations='filesystem:sql/'  -outOfOrder=true migrate
      # - run: flyway -user='gdhawas' -password='SFgrd0710*' -url='jdbc:snowflake://pm71396.ap-south-1.aws.snowflakecomputing.com/?db=QA_DB&warehouse=QA&schema=FLYWAY' -locations='filesystem:sql/' migrate
      - run: flyway -user='ADWAITATGEIR' -password='Pass12345*' -url='jdbc:snowflake://vl52144.ap-south-1.aws.snowflakecomputing.com/?db=QA_DB&warehouse=QA&schema=FLYWAY' -locations='filesystem:sql/' -baselineOnMigrate="true" migrate


workflows:
  version: 2
  test_2:
    jobs:
      - flyway-build

